### ISSUE TITLE
hierarchy UIDataGrid

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#117]
Hi,
Is it possible at uidatagrid v4 this senario (like sub data in version 3 but to other table) :
Main grid (Show all rows from Groups table)

ID   Name           Members
1    Group 1        SubGrid (Show rows from Members table where Members.GroupID=Current row's GroupID)
2    Group 2        SubGrid (show members in group 2)
3    Group 3        SubGrid (show members in group 3)

Thanks

**Comment by avrahamcool** [comment]
In the current implementation - you can't (at least not easily).
I think the current behavior of the `nested view` in the grid is very wrong because it's expecting a string literal for the `nested  view` component. and it's very limiting.
I think the `nested view` should be implemented with compose.
each grid (or preferably, each row) can indicate a `view` and `view model` for the compose tag, and the `model` that will get past is the row itself, then you can create whatever you want inside the `nested view` including a `sub grid` which will be a another regular grid...

@adarshpastakia what do you say?
