### ISSUE TITLE
DataSource

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#21]
> DataSource implementation for data components

##### Affected Components

* (!!!) Datagrid
* (!!) Combo
* (!!) List
* (!!) Tags
* (!) Tree
* (!) Textarea auto-complete

##### BaseDataSource

```ts

fetchData(): Promise | Array
loadPage(n): Promise | Array
loadSummary(): Promise | Array

sort(dataId, order): Promise | Array
filter({ dataId: value }): Promise | Array

```

###### LocalData

```ts
constructor(Array)

remoteSorting = false
remoteFilter = false
remoteSummary = false
```

###### RemoteData
Can implement `RemoteData` in an extended class to override base methods

```ts
constructor(Array)

url
dataProperty = 'data'
pageProperty = 'page'
totalProperty = 'records'

remoteSorting = optional
remoteFilter = optional
remoteSummary = optional
```

**Comment by adarshpastakia** [comment]
Created initial implementation for Local DataSource in Release 3.1.14

**Comment by avrahamcool** [comment]
it'll be very helpful if the DataSource will support OData [standard](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html) out of the box (or at least an easy way to tune it to OData).
1) order/filter on multiple columns (with order between them)
2) skip & top for paging (instead of loadPage(n) as suggested here)
 more advance features would be the aggregations, drill downs etc.

can I hep in any way? to make that happen?

**Comment by adarshpastakia** [comment]
#69
