### ISSUE TITLE
Rework UIModel and UIDataSource

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#69]
# Data-Model and Data-Source

----

## DataModel

1. Add option for URL for CRUD
  * `/api/user` which will be used for following
    * `GET /api/user/:id`
    * `POST /api/user/`
    * `PUT /api/user/:id`
    * `DELETE /api/user/:id`
* All operations will provide `isBusy` indicator
* Add decorator `@ignoreSerialize` to ignore given property from serialization
* Observe all model property keys to update `dirty` and `propDirty` indicators (Need to think about structuring the propDirty)
* Are three model states required? This will be useful when using the model in a DataSource
  * `__original__` maintains the original record
  * `__updated__` maintains updated values that have not been synced via the API
  * `discardChanges()` will revert to the `__updated__` dataset
  * `reset()` will revert to the `__original__` dataset

### Initial Thoughts
```ts
// Since there is no objectObservation need to rely on propertyObserver for updating the dirty indicators
// Update property dirty on propertyObserve callback
init() {
  each(keys, key=>observe(prop, ()=>this.propChange(key)));
}

propChange(key) {
  return ()=>this.checkDirty(
    this.propDirty[key] = this.__original__[key]!==this[key]);
}

discard() {
  each(keys, key=>this[key] = this.__updated__[key]);
}

reset() {
  each(keys, key=>this[key] = this.__updated__[key] = this.__original__[key]);
}
```

---

## Remote DataSource
1. Add option for URL for CRUD
  * `/api/user` which will be used for following
    * `GET /api/users` fetch all models
    * `POST /api/user/`
    * `PUT /api/user/:id`
    * `DELETE /api/user/:id`
    > Do we follow singular calls for all updates and deletes
    > Or do we create a single call with multiple update models
    > eg. DELETE /api/users body=[1,2,3]
* Observe the dirty property of all models to maintain dirty indicator for the store
* Need to have server side sorting, pagination and filter capabilities
  * Filter is important when using stores with lists and auto-complete

**Comment by adarshpastakia** [comment]
Since I'm not much into data objects and models, trying to work out the best approach to models and data-sources.

**Comment by avrahamcool** [comment]
I think the `DataModel` proposed here still have 2 main concerns that should be seperated.
1) Data concerns. (how the data is structured + dirty tracking) should be under `UIModel`
2) Service concerns. (how do we fetch the data? how to update the server? + busy/error tracking) should be under `UIService`.

you already have a class called `UIHttpService` - but he has the functionality of a HttpClient, so maybe he should be renamed to `UIHttpClient`?

the implementation for dirty tracking that is shown here will work for primitives, but will fail for reference type (objects, array, maps etc.) because the equality check will test for reference equality and not content equality.
also, we don't really need `dirty` and `dirtyProp` - the property should suffice. (I was afraid of breaking changes so I left the `dirty` function - but if we do a rework on that, maybe we should leave it off).

about the remote data source - it would be very nice to support `patch` as well as `put` (`patch` is the prefferd way in some api implementations).

_the datasource classes (remote and local) inherits from a common class `UIDataSource` (who also inherits from `UIService`)
and each specsific DS needs to implement the function as he want. (remote, local etc...)_
--I didn't think think through - maybe we can improve that part.

I think singular calles are better (for the remote DS) because the server's API works like that. (at least all those I know).

I created a class diagram to demostrate how I see those classes (the diagram can be duplicated and edited) - what do you think about that approach?
https://www.gliffy.com/go/html5/12181800

**Comment by adarshpastakia** [comment]
@avrahamcool unable to open the link, getting a 401.

I kinda took this idea from having worked with Sencha ExtJS stores and models. Where a model can act as a singular entity or as part of a store, and both can have a proxy property that performs the server actions, so the idea of the service would be similar to the proxy. I maybe over-complicating it in my head but there are too many scenarios to consider, maybe need to workout a simple foundation for the data models and stores.

however we change it around, I'm hoping to do this on the v4 branch trying to avoid breaking the current v3 version.

**Comment by avrahamcool** [comment]
my bad, forgot to make it public.
here is the public [link](https://www.gliffy.com/go/share/swxp9f107do75e3g6nsr).

**Comment by avrahamcool** [comment]
also, it whould be benificial to take a look at the `DataSource` implementation of `KendoUI`.
they have a powerfull and clean implementation of `Model`, `Schema`, `DataSource` etc..

**Comment by avrahamcool** [comment]
I came across [breeze](http://breeze.github.io/doc-js/ ) open source js library for managing data on the client.

it has all what we are talking about here and more (client caching, ODATA services, detecting models dynamically from your server, rich entity management API, events handling, js data query language and more).

they supports binding with aurelia natively.

can we incorporate that into the framework instead of creating it ourself?

**Comment by delebash** [comment]
A few more frameworks [js-data](https://github.com/js-data/js-data) and [jaydata](http://jaydata.org)

Spoonx [aurelia-api](https://github.com/SpoonX/aurelia-api) as well as [authorization](https://github.com/SpoonX/aurelia-authentication) and [orm](https://github.com/SpoonX/aurelia-orm)

Having said that I have used kendo's datasource and it works well.

Regarding breeze there is an aurelia [plugin](https://github.com/jdanyow/aurelia-breeze) for it

**Comment by avrahamcool** [comment]
js-data looks like a very good option.
@adarshpastakia what are your thoughts on this?

**Comment by adarshpastakia** [comment]
@avrahamcool just glanced through it a bit, need to see how best we can make use of it. we need a model+store for local and remote data, will try it out later. For now I'm trying to get the v4 build to work on webpack.
