### ISSUE TITLE
[Improvement] use @types instead of typings

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#72]
The (new) preffered way to handle TypeScript type definitions is by using `@types` instead of `typings`.
it should be an easy and transparent fix.

can we push that to version 4 (or even to master)?

**Comment by avrahamcool** [comment]
I realized that by deleting the `aurelia-protractor.d.ts` file that was in `custom_typings` the project compiles fine. even without installing any typings at all.
[before that, I would have to run `typings install` that would install a bunch of unnecessary stuff].
Is it ok? am I missing something?

also: i see that the project is a cli project, but it also has a `jspm` section in the `package.json`.
is it a mistake? what is the purpose of `jspm` in the project?

and finally, the cli has been updated a ton of times (including the latests version with webpack).
do you plan to update the project accordingly?

**Comment by adarshpastakia** [comment]
if it works ok without typings then we can make the necessary update.

haven't looked into the latest cli changes, maybe need to try running the project with latest cli to see what breaks.

as for jspm, I had received a pr for it since they were using jspm for their project, so I left it in case some want to use jspm.

**Comment by avrahamcool** [comment]
@adarshpastakia 
can we close this?
I think you implemented that in V4.

**Comment by adarshpastakia** [comment]
Fixed in version 4
