### ISSUE TITLE
[Feature Request] support font-awesome icons for glyph

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#94]
Hi @adarshpastakia ,
can we add support for [font-awesome](http://fontawesome.io/icons/) icons.
I mean that every place that can take a `glyph` could also receive a font-awesome icon.
they have a huge and diverse library of icons, and currently are working on a new version with a lot of cool stuff.

I don't know how the glyph are implemented - so I'm not able to do it myself.

**Comment by adarshpastakia** [comment]
Hi @avrahamcool, you can try this for now.
```html
<ui-glyph class='fa fa-envelope'></ui-glyph>
```

for the upcoming version will probably add a `fa` attribute and use `<i class='fa'>..` instead of svg,
however i just realized the trouble with that would be components like buttons, menu items where they pass-on the `glyph` attribute to `ui-glyph` will need `fa` attribute as well.

for now if needed you could try the updating the following code in `ui-pages.ts` and see if thats a good solution to begin with

```
@customElement('ui-glyph')
@inlineView(`<template class="ui-icon \${glyph}"><svg if.bind="glyph"><use tabindex="-1" x="0" y="0" xlink:href="#\${glyph}"/></svg></template>`)
export class UIGlyph {
  constructor(public element: Element) { }
  @bindable() glyph = '';
}
```

**Comment by adarshpastakia** [comment]
@avrahamcool  https://adarshpastakia.github.io/auf-demo-v4/#/buttons the sized buttons are using fa icons

**Comment by avrahamcool** [comment]
@adarshpastakia the sized icons are not showing the fa icons.
maybe the `css` file is missing?
![image](https://user-images.githubusercontent.com/5445320/32446532-e0f4c63c-c311-11e7-9603-22d020a65f73.png)

**Comment by adarshpastakia** [comment]
@avrahamcool  Try a refresh, i included the fontawesome stylesheet via a cdn

<img width="607" alt="screen shot 2017-11-06 at 10 35 53 pm" src="https://user-images.githubusercontent.com/6481108/32453673-f67a2e9e-c342-11e7-93b7-af1b9ee6b4b2.png">
